trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# 🔥 Add this
- script: dotnet restore **/*.csproj
  displayName: Restore

- script: dotnet build **/*.csproj --no-restore
  displayName: Build

- script: dotnet test **/*.csproj --logger "trx"
  displayName: Run Tests
