trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore SeleniumUIAutomation.sln
  displayName: Restore

- script: dotnet build SeleniumUIAutomation.sln --no-restore
  displayName: Build

- script: dotnet test SeleniumUIAutomation.sln --logger "trx"
  displayName: Run Tests

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

- script: dotnet publish SeleniumUIAutomation.sln -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: Publish Project

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: 'FullOutput'