trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore
  displayName: Restore

- script: dotnet build --no-restore
  displayName: Build

- script: dotnet test --logger "trx"
  displayName: Run Tests